wandb_version: 1

do_wandb_logging:
  desc: null
  value: true
actor_units:
  desc: null
  value:
  - 256
  - 256
actor_learning_rate:
  desc: null
  value: 0.002
actor_learning_rate_schedule:
  desc: null
  value: constant
critic_units:
  desc: null
  value:
  - 256
  - 256
critic_learning_rate:
  desc: null
  value: 0.0005
critic_learning_rate_schedule:
  desc: null
  value: constant
critic_minibatches:
  desc: null
  value: 4
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.995
num_steps:
  desc: null
  value: 32
num_envs:
  desc: null
  value: 64
max_epochs:
  desc: null
  value: 2000
critic_iterations:
  desc: null
  value: 16
dt:
  desc: null
  value: 0.005
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721246194.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.11.8
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      6:
      - 3
    - 1: step
      6:
      - 3
    - 1: step/actor_loss
      5: 2
      6:
      - 1
    - 1: step/critic_loss
      5: 2
      6:
      - 1
    - 1: step/learning_episode_rewards
      5: 2
      6:
      - 1
    - 1: epoch/actor_loss
      5: 1
      6:
      - 1
    - 1: epoch/critic_loss
      5: 1
      6:
      - 1
    - 1: epoch/learning_episode_rewards
      5: 1
      6:
      - 1
    - 1: step/episode_rewards
      5: 2
      6:
      - 1
    - 1: epoch/episode_rewards
      5: 1
      6:
      - 1
