wandb_version: 1

do_wandb_logging:
  desc: null
  value: true
actor_units:
  desc: null
  value:
  - 64
  - 64
actor_learning_rate:
  desc: null
  value: 0.001
actor_learning_rate_schedule:
  desc: null
  value: linear
critic_units:
  desc: null
  value:
  - 64
  - 64
critic_learning_rate:
  desc: null
  value: 0.001
critic_learning_rate_schedule:
  desc: null
  value: linear
critic_minibatches:
  desc: null
  value: 4
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.2
num_steps:
  desc: null
  value: 32
num_envs:
  desc: null
  value: 64
max_epochs:
  desc: null
  value: 2000
critic_iterations:
  desc: null
  value: 16
dt:
  desc: null
  value: 0.01
device:
  desc: null
  value: cuda
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721067958
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 7
      - 16
      - 23
      4: 3.11.9
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch
      6:
      - 3
    - 1: step
      6:
      - 3
    - 1: step/loss
      5: 2
      6:
      - 1
    - 1: step/accuracy
      5: 2
      6:
      - 1
    - 1: epoch/loss
      5: 1
      6:
      - 1
